spring:
  application:
    name: example-service
  profiles:
      active: local

server:
  port: 10003

---
###################  开发环境的profile  ###################
spring:
  profiles: local

eureka:
  instance:
      hostname: service1
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/