spring:
  application:
    name: zuul
  profiles:
      active: local

server:
  port: 10002

zuul:
  retryable: true   #转发重试关闭
  routes:
    example-service:
      path: /example-service/**
      serviceId: example-service

#服务调用超时配置
hystrix:
  command:
    example-service:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 12000   #hystix的连接超时时间

example-service:
  ribbon:
    ConnectTimeout: 1500 #创建连接的超时时间
    ReadTimeout: 2000 #路由转发请求的超时时间
    OkToRetryOnAllOperations: true
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 5

---
###################  开发环境的profile  ###################
spring:
  profiles: local

eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/